version: 2
jobs:
  package:
    working_directory: ~/RTKPythonPackage-build
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:34:a3:8d:e0:f6:6d:3f:9b:75:f1:bb:60:ee:59:c1"
      - checkout:
          path: ~/RTKPythonPackage
      - run:
          name: Configure
          no_output_timeout: 1.0h
          command: |
            cmake ~/RTKPythonPackage


workflows:
    version: 2
    build-test:
      jobs:
        - package
