version: 2
jobs:
  package:
    working_directory: ~/RTKPythonPackage-build
    machine: true
    steps:
      - add_ssh_keys:
        fingerprints:
          - "cf:34:a3:8d:e0:f6:6d:3f:9b:75:f1:bb:60:ee:59:c1"
      - checkout:
          path: ~/RTKPythonPackage
      - run:
          name: Configure
          no_output_timeout: 1.0h
          command: |
            cmake ~/RTKPythonPackage
		- run:
                  name: Fetch build script
                  command: |
                    curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITKPythonPackage/v4.13.1.post1/requirements-dev.txt -O
                    curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITKPythonPackage/v4.13.1.post1/scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh -O
                    chmod u+x dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - run:
          name: Build Python packages
          no_output_timeout: 1.0h
          command: |
            export ITK_PACKAGE_VERSION="v4.13.1.post1"
            chmod u+x BuildLinuxWheels.sh
            ./BuildLinuxWheels.sh
      - store_artifacts:
          path: ~/RTKPythonPackage-build/RTK/dist
workflows:
    version: 2
    build-test:
      jobs:
        - package
